seed: 42
model_type: 'fusion' # 'confidence', 'text_only', 'fusion'
model_name: "bert-base-uncased" # Model used for classification
num_classes: 2
max_len: 288
n_splits: 10 # Use 1 for a single train/validation split, >1 for cross-validation
validation_split_fraction: 0.2 # Used only when n_splits is 1
num_hypotheses: 5 # How many hypotheses to use for training the classifier
results_root: "results" # Base directory for all outputs (transcripts, models, plots)

training:
  learning_rate: 2.0e-5
  epochs: 10
  batch_size: 32
  patience: 3
  gradient_clip_norm: 0.0 # Use 0 to disable
  warmup_fraction: 0.1

data:
  train_audio_root: "data/ADReSSo21-diagnosis-train/ADReSSo21/diagnosis/train/audio"
  test_audio_root: "data/ADReSSo21-diagnosis-test/ADReSSo21/diagnosis/test-dist/audio"
  test_labels_csv: "data/label_test_task1.csv"
  processed_data_dir: "data/processed" # Directory for generated train.csv/test.csv

feature_extraction:
  model_name: "facebook/wav2vec2-large-960h-lv60-self"
  output_root: "results/features"

fusion_model:
  acoustic_feature_layer: "layer_10" 
  acoustic_dim: 1024
  classifier_hidden_size: 1024
  reduced_acoustic_dim: 256

transcription:
  # Choose between 'whisperx' or 'wav2vec2'
  model_type: "wav2vec2"
  
  whisperx_options:
    #model_name: "large-v3"
    model_name: "nyrahealth/faster_CrisperWhisper"
    device: "cuda"
    compute_type: "float32"
    # The number of hypotheses to generate. This sets both 'best_of' and 'beam_size'.
    n_hypotheses: 30
    batch_size: 16 # Internal batch size for processing segments of a single audio file.

  wav2vec2_options:
    acoustic_model_name: "facebook/wav2vec2-large-960h-lv60-self"
    base_processor_name: "facebook/wav2vec2-large-960h-lv60-self"
    #acoustic_model_name: "jonatasgrosman/wav2vec2-large-xlsr-53-english"
    #base_processor_name: "jonatasgrosman/wav2vec2-large-xlsr-53-english"
    #lm_repo_id: "BramVanroy/kenlm_wikipedia_en"
    #lm_filename: "wiki_en_token.arpa.bin"
    lm_repo_id: "patrickvonplaten/wav2vec2-base-100h-with-lm"
    lm_filename: "language_model/4-gram.bin"
    lm_unigrams_filename: "language_model/unigrams.txt"

    device: "cuda"
    batch_size: 8 # Number of audio files to process in a single batch.
    # Parameters to generate 30 hypotheses (10 alphas * 3 betas)
    num_alphas: 10
    min_alpha: 0.4
    max_alpha: 1.8
    num_betas: 3
    min_beta: 0.0
    max_beta: 1.5
